version: "3.8"

services:
  mariadb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPASSWORD
      MYSQL_DATABASE: SITE_DB
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/tmp/init.sql
    command: ["--init-file", "/tmp/init.sql"]
    depends_on:
      - webserver
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SITE_DB_PASSWORD: rootPASSWORD
      SESSION_KEY: 8D28E179A8226396169CC074AE0DE76A
  caddy:
    image: caddy:latest
    volumes:
      - ./Config/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "443:443"
