CREATE DATABASE SITE_DB;
USE SITE_DB;
CREATE TABLE IF NOT EXISTS USER (id INT AUTO_INCREMENT PRIMARY KEY,email TEXT,password TEXT);
CREATE TABLE IF NOT EXISTS ATTRACTION_ENTRY(id AUTO_INCREMENT INTEGER PRIMARY KEY,title varchar(64),type varchar(32),recommended_count int,city Text,info Text,PosX Float,PosY Float);



